apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo_app
  template:
    metadata:
        name: app
        labels:
          app: demo_app
    spec:
      containers:
        - name: nginx
          image: hello12/nginx_kubenetes
          ports:
            - name: port
              containerPort: 80
        - name: php
          image: hello12/php_client
          ports:
            - name: port
              containerPort: 9000
    