apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo_app
  template:
    metadata:
        name: app
        labels:
          app: demo_app
    spec:
      containers:
        - name: nginx
          image: hello12/nginx_kubenetes
          ports:
            - name: port
              containerPort: 80
        - name: php
          image: hello12/php_client
          env:
            - name: api_url
              value: https://jsonplaceholder.typicode.com/posts/1
          ports:
            - name: port
              containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
      app: demo_app
  type: ClusterIP
  ports:
    - name: port1
      port: 80
      targetPort: 80
    